name: flutter_boilerplate
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  auto_route: ^6.0.1
  busbus: ^0.1.3
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_localization: ^3.0.1
  firebase_core: ^2.8.0
  firebase_dynamic_links: ^5.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.18

dev_dependencies:
  auto_route_generator: ^6.0.0
  build_runner: null
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/i10n/
    - .env
